/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SensorListRouteImport } from './routes/sensor-list'
import { Route as SensorDatabaseRouteImport } from './routes/sensor-database'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SensorsSensorIdRouteImport } from './routes/sensors.$sensorId'
import { Route as SectionsSectionIdRouteImport } from './routes/sections.$sectionId'
import { Route as LinesLineIdRouteImport } from './routes/lines.$lineId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as FactoriesFactoryIdRouteImport } from './routes/factories.$factoryId'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorListRoute = SensorListRouteImport.update({
  id: '/sensor-list',
  path: '/sensor-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorDatabaseRoute = SensorDatabaseRouteImport.update({
  id: '/sensor-database',
  path: '/sensor-database',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsSensorIdRoute = SensorsSensorIdRouteImport.update({
  id: '/sensors/$sensorId',
  path: '/sensors/$sensorId',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsSectionIdRoute = SectionsSectionIdRouteImport.update({
  id: '/sections/$sectionId',
  path: '/sections/$sectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LinesLineIdRoute = LinesLineIdRouteImport.update({
  id: '/lines/$lineId',
  path: '/lines/$lineId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoriesFactoryIdRoute = FactoriesFactoryIdRouteImport.update({
  id: '/factories/$factoryId',
  path: '/factories/$factoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/sensor-database': typeof SensorDatabaseRoute
  '/sensor-list': typeof SensorListRoute
  '/settings': typeof SettingsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/factories/$factoryId': typeof FactoriesFactoryIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/lines/$lineId': typeof LinesLineIdRoute
  '/sections/$sectionId': typeof SectionsSectionIdRoute
  '/sensors/$sensorId': typeof SensorsSensorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/sensor-database': typeof SensorDatabaseRoute
  '/sensor-list': typeof SensorListRoute
  '/settings': typeof SettingsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/factories/$factoryId': typeof FactoriesFactoryIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/lines/$lineId': typeof LinesLineIdRoute
  '/sections/$sectionId': typeof SectionsSectionIdRoute
  '/sensors/$sensorId': typeof SensorsSensorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/sensor-database': typeof SensorDatabaseRoute
  '/sensor-list': typeof SensorListRoute
  '/settings': typeof SettingsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/factories/$factoryId': typeof FactoriesFactoryIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/lines/$lineId': typeof LinesLineIdRoute
  '/sections/$sectionId': typeof SectionsSectionIdRoute
  '/sensors/$sensorId': typeof SensorsSensorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/login'
    | '/sensor-database'
    | '/sensor-list'
    | '/settings'
    | '/companies/$companyId'
    | '/factories/$factoryId'
    | '/groups/$groupId'
    | '/lines/$lineId'
    | '/sections/$sectionId'
    | '/sensors/$sensorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/login'
    | '/sensor-database'
    | '/sensor-list'
    | '/settings'
    | '/companies/$companyId'
    | '/factories/$factoryId'
    | '/groups/$groupId'
    | '/lines/$lineId'
    | '/sections/$sectionId'
    | '/sensors/$sensorId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/sensor-database'
    | '/sensor-list'
    | '/settings'
    | '/companies/$companyId'
    | '/factories/$factoryId'
    | '/groups/$groupId'
    | '/lines/$lineId'
    | '/sections/$sectionId'
    | '/sensors/$sensorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  SensorDatabaseRoute: typeof SensorDatabaseRoute
  SensorListRoute: typeof SensorListRoute
  SettingsRoute: typeof SettingsRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  FactoriesFactoryIdRoute: typeof FactoriesFactoryIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  LinesLineIdRoute: typeof LinesLineIdRoute
  SectionsSectionIdRoute: typeof SectionsSectionIdRoute
  SensorsSensorIdRoute: typeof SensorsSensorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-list': {
      id: '/sensor-list'
      path: '/sensor-list'
      fullPath: '/sensor-list'
      preLoaderRoute: typeof SensorListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-database': {
      id: '/sensor-database'
      path: '/sensor-database'
      fullPath: '/sensor-database'
      preLoaderRoute: typeof SensorDatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors/$sensorId': {
      id: '/sensors/$sensorId'
      path: '/sensors/$sensorId'
      fullPath: '/sensors/$sensorId'
      preLoaderRoute: typeof SensorsSensorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections/$sectionId': {
      id: '/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/sections/$sectionId'
      preLoaderRoute: typeof SectionsSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lines/$lineId': {
      id: '/lines/$lineId'
      path: '/lines/$lineId'
      fullPath: '/lines/$lineId'
      preLoaderRoute: typeof LinesLineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factories/$factoryId': {
      id: '/factories/$factoryId'
      path: '/factories/$factoryId'
      fullPath: '/factories/$factoryId'
      preLoaderRoute: typeof FactoriesFactoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  SensorDatabaseRoute: SensorDatabaseRoute,
  SensorListRoute: SensorListRoute,
  SettingsRoute: SettingsRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  FactoriesFactoryIdRoute: FactoriesFactoryIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  LinesLineIdRoute: LinesLineIdRoute,
  SectionsSectionIdRoute: SectionsSectionIdRoute,
  SensorsSensorIdRoute: SensorsSensorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
